lsi:         false
port:        4000
highlighter: pygments
markdown:    rdiscount
rdiscount:   { extensions: [smart] }
permalink:   /:year/:month/:title/
exclude:
- bin
- script
- Gemfile
- Gemfile.lock
- vendor
