auto:        false
lsi:         false
server:      false
server_port: 4000
pygments:    true
markdown:    rdiscount
rdiscount:   { extensions: [smart] }
permalink:   /:year/:month/:title/
exclude:
- draft
- publish
- CNAME
- Guardfile
- stylesheets/default.sass

tracking_code: |
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-87067-3']);
  _gaq.push(['_trackPageview']);
  if (!/local|\.dev$/.test(location.hostname)) (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    var t = document.createElement('script'); t.type = 'text/javascript'; t.async = true;
    t.id = 'gauges-tracker'; t.setAttribute('data-site-id', '4e1d9163f5a1f56fd4000003');
    t.src = '//secure.gaug.es/track.js';
    s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(t, s);
  })();
extra_tracking_code: |
  if ('addEventListener' in document) (function(){
    var root = 'http://' + location.host + '/'

    function isLink(elem) {
      return elem.nodeType == Node.ELEMENT_NODE &&
        elem.nodeName.toUpperCase() == 'A' &&
        typeof elem.getAttribute('href') == 'string'
    }

    function findLink(elem, limit) {
      if (limit > 0 && elem) {
        return isLink(elem) ? elem : findLink(elem.parentNode, limit - 1)
      }
    }

    document.addEventListener('click', function(e) {
      if (!window._gaq || e.which == 3) return // ignore right click
      var trackData, link = findLink(e.target, 3)
      if (link) {
        if (link.href.replace(/^https:/i, 'http:').indexOf(root) !== 0) {
          // track outbound links
          var domain = link.href.split('/', 3)[2]
          trackData = ['_trackEvent', 'Outbound links', domain]
        }
        else if (/.(\w{2,5})$/.test(link.href) && RegExp.$1.toLowerCase() != 'html') {
          // track file downloads
          var path = '/' + link.href.replace(root, '')
          trackData = ['_trackPageview', path]
        }

        if (trackData) {
          _gaq.push(trackData)
          if (e.which == 1 && !(e.ctrlKey || e.metaKey || e.shiftKey)) {
            // on regular left click, force a small delay before following the link
            setTimeout(function(){ document.location = link.href }, 100)
            e.preventDefault()
          }
        }
      }
    })
  })()
