auto:        false
lsi:         false
server:      false
server_port: 4000
pygments:    true
markdown:    rdiscount
rdiscount:   { extensions: [smart] }
permalink:   /:year/:month/:title/
destination: public
exclude:
- bin
- CNAME
- Guardfile
- default.sass
